### ISSUE TITLE
Suggestion to improve build.csh

### ISSUE THREAD

**Issue by yvikhlya** [GEOS-ESM/ESMA_env#20]
Let user specify custom Pbuild_build_directory and Pbuild_install_directory environments. This would simplify making multiple builds from different branches. For example, if a user wants to test a feature branch alongside  with develop branch, it could be done in two steps:
`$./checkout_externals -e Feature.cfg` (checks out a feature branch)
`$./parallel_build.csh -build-dir build-feature -install-dir install-feature` (makes another build)
Does this make sense?

**Comment by mathomp4** [comment]
@yvikhlya This should be doable. I'll try to have a fix for this and #18 soon.

**Comment by mathomp4** [comment]
@yvikhlya Can you try out branch `feature/mathomp4/#18-#20-fixqueue-and-add-dirs`. I added two new options:
```
   -builddir dir        alternate CMake build directory (relative to $ESMADIR)
   -installdir dir      alternate CMake install directory (relative to $ESMADIR)
```
I decided against the extra hyphens in the options just because other bits of `parallel_build` didn't have them.

NOTE: It's only relative to `$ESMADIR` at the moment. The script would need a good think to support out-of-ESMADIR building. Not impossible, but I did the easy stuff first.

**Comment by yvikhlya** [comment]
@mathomp4 yes, this worked for me.
