### ISSUE TITLE
typo in master and release

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/ESMA_env#38]
@mathomp4 There is typo in the master and some releases. The string on compiler and the base lib should be 19.1.0.166,  not 19.0.1.166

**Comment by mathomp4** [comment]
@weiyuan-jiang There was indeed a bug in yours, but master is okay:
https://github.com/GEOS-ESM/ESMA_env/blob/feb19e6cb89e1fce72311cab6aea27952d684665/g5_modules#L138-L142

I pushed the tag I gave you since, well, no one could use it.

**Comment by weiyuan-jiang** [comment]
Why not put the sles 11 into the tag you give to GEOSldas? I think it is helpful

**Comment by mathomp4** [comment]
> Why not put the sles 11 into the tag you give to GEOSldas? I think it is helpful

Because then you would have two different compilers one of which you have already said could have issues.

As I said to Rolf, Intel 19 will not and *cannot* be installed on SLES 11. Period. Intel's installer *will not* work on SLES 11. The OS is too old. If you want to use Intel 19, you can *only* be on SLES 12. Period. 

If you want a mixed Intel 18 on SLES 11/Intel 19 on SLES 12, I can do that, but I will accept no responsibility if a binary output is incorrect because of an issue you already know about with Intel 18. I will automatically close any ticket that might have to do with binary output as "Will not fix" if it involves Intel 18.

**Comment by mathomp4** [comment]
The other thing I could do is provide GCC 9 on SLES 11 if that is okay. But then the answers would be quite different I imagine on each system. But as far as I know, you have not found any binary-output issues with GCC in regards to GEOSldas/LDASsa. 

But the users would need to know that they were running a different compiler (and MPI stack) when on the other system.

**Comment by mathomp4** [comment]
This does bring up a good point. I think I need to make a "validate g5_modules" script. As in every time I make one up, I should run the script on it and have it give "PASS/FAIL" output. So many numbers in those files, and typos are hard to spot. 

I might ask you to be a tester of it once I get something working...

**Comment by tclune** [comment]
Unfortunately, you could only test it in the current environment, right?    It would be nice to somehow validate at NAS and locally on SLES 11 & 12 simultaneously.

**Comment by mathomp4** [comment]
@tclune Yeah. It's not perfect. But, I could maybe use `ssh pfe validate.csh`? There must be a way...

**Comment by mathomp4** [comment]
Of course, that means a script to call the validation script! :)

**Comment by weiyuan-jiang** [comment]
The issue with Intel 18 is on SLES12. For SLES 11, Intel 18 is fine. So I would like the g5_module with both Intel 18 ( sles 11) and Intel 19 (sles12) @mathomp4

**Comment by mathomp4** [comment]
@weiyuan-jiang Okay. Can you try out the version on the *branch* `release/2.0.4+intel19.1`. If you say it works on SLES 11 and SLES 12, I'll tag it with something like:
```
v2.0.4+intel19.1.0+intel18.0.5_sles11
```
or something...ugly.

**Comment by weiyuan-jiang** [comment]
@mathomp4 . Thanks. I will test it.

**Comment by weiyuan-jiang** [comment]
problem solved.
